### ISSUE TITLE
Make default failure handler accessible

### ISSUE THREAD

**Issue by DNKpp** [jeremy-rifkin/libassert#109]
Today I found myself trying to extend the default failure handler mechanism. In fact I simply wanted to write a logging output and than hand the assertion over to the default handler.
The readme has an (slightly outdated) example for that ( it shows an additional ``type`` parameter for the handler), but unfortunately I'm not able to just extend the handler, because the default handler is not visible to the users.
As I'm linking statically I made it visible by forward declaring ``libassert::detail::libassert_default_failure_handler(const assertion_info& info)`` in my own translation unit, but this feels rather hacky.

Is there a particular reason to not allow users to *extend* the default handler?

**Comment by jeremy-rifkin** [comment]
Hi @DNKpp,
My thought process at the time was that if a user wanted to do any special behavior in the handler they probably need control over most of what's currently done in `libassert_default_failure_handler`, e.g. control over exiting or control over how the message is formatter or what's done with the message etc. Basically, there are a lot of shapes extending the default handler could take and instead of trying to support them all I figured a user should just copy it if they wanted to make their own.

However, you bring up a good use-case for how it could be useful and convenient to be able to call `libassert_default_failure_handler` after some simple custom handling so I'd be happy to make it public.

Thanks for mentioning the readme example being outdated, I'll fix that.

**Comment by DNKpp** [comment]
Thank you for your reply. When you give that change a go, I think we should mark the default handler with ``[[noreturn]]``, shouldn't we?

**Comment by jeremy-rifkin** [comment]
Yes I think the default handler may as well be marked `[[noreturn]]`.

As far as static init order goes, I could imagine scenarios where that's relevant for this handler. I'm not immediately seeing how function-local static variables could help, though. What do you have in mind?

**Comment by DNKpp** [comment]
Well, in fact I would like to install my default handler without writing my own main function, as this has to be done for each and any test-executable.
So I ended up with that tiny pattern:
```cpp
namespace internal
{
    class FailureHandlerInstaller
    {
    public:
        explicit FailureHandlerInstaller(void (*handler)(const libassert::assertion_info&))
		{
        	libassert::set_failure_handler(handler);
    	}
    };

    [[maybe_unused]]
    inline volatile const FailureHandlerInstaller installer{&assertion_handler};
}
```

I don't know exactly how cmake rolls out the linking order, but currently that works well. This is code, which is located in my own binary, which links to ``libassert``.
Changing the ``libassert``-code to this, should make it standard-compliant without any negative side-effect (at least I'm not aware of any).
```cpp
// current code
static std::atomic failure_handler = detail::libassert_default_failure_handler;

// to this
[[nodiscard]]
auto& failure_handler() {
    static std::atomic handler = detail::libassert_default_failure_handler;
    return handler;
}
```

**Comment by jeremy-rifkin** [comment]
Thanks, that sort of approach for static init is good. I've done some of the changes discussed here in 3bf1bc6f7372e0d4e49f2d3100f6a2fd39a6a451, I'll make some changes to safeguard against potential static init order issues.

**Comment by jeremy-rifkin** [comment]
2.1.3 is released

**Comment by DNKpp** [comment]
Thank you very much!
