### ISSUE TITLE
UWP support

### ISSUE THREAD

**Issue by JaiganeshKumaran** [jeremy-rifkin/libassert#83]
The vcpkg website shows that UWP targets are supported, nevertheless, I'm still getting the following errors while building:
```cpp
1>cpptrace is only supported on '!uwp', which does not match x64-uwp. This usually means that there are known build failures, or runtime problems, when building other platforms. To ignore this and attempt to build cpptrace anyway, rerun vcpkg with `--allow-unsupported`.
1>libassert is only supported on '!uwp', which does not match x64-uwp. This usually means that there are known build failures, or runtime problems, when building other platforms. To ignore this and attempt to build libassert anyway, rerun vcpkg with `--allow-unsupported`.
 ```
<img width="918" alt="Screenshot 2024-03-09 at 02 19 40" src="https://github.com/jeremy-rifkin/libassert/assets/45227503/2411ef25-42b6-4200-bf11-9688d29605d4">

**Comment by jeremy-rifkin** [comment]
Hi, both vcpkg.json files for cpptrace https://github.com/microsoft/vcpkg/blob/0719a71389654b88d827501d88e37e58ea8cbd70/ports/cpptrace/vcpkg.json#L7 and libassert https://github.com/microsoft/vcpkg/blob/0719a71389654b88d827501d88e37e58ea8cbd70/ports/libassert/vcpkg.json#L8 are set to not support UWP. I think an issue should be opened on the vcpkg repo regarding what the website says.

As far as adding support in the future, iirc there were issues with cpptrace due to needing dbghelp.

**Comment by jeremy-rifkin** [comment]
I have reported this upstream at https://github.com/microsoft/vcpkg/issues/37493
