### ISSUE TITLE
Compilation error if asserted member value belongs to packed struct

### ISSUE THREAD

**Issue by yfinkelstein** [jeremy-rifkin/libassert#88]
```
struct PackedStruct {
int a;
short b;
long c:
} __attribute__((packed));
```

`PackedStruct s;`
..

`ASSERT(s.a == 0)`
results in a compilation error when using( a recent) gcc.
This is apparently a known issue - one cannot obtain a reference to a packed member according to C++ standard.

**Comment by jeremy-rifkin** [comment]
Thank you for opening this, I'd never thought about this :) I don't immediately know the best way to support packed members but I will investigate.

**Comment by jeremy-rifkin** [comment]
Bit-fields are also affected

**Comment by jeremy-rifkin** [comment]
I've played around with this a little bit and unfortunately I think there's no way from a library standpoint to make this work on gcc. It does work on clang.

In order to support this directly in the library, I'd essentially need a way to make the following code work where the `&&` is automatically not a reference when it can't be one (though that itself would have its own set of design considerations such as introducing a potential footgun of accidentally copying)
```cpp
struct __attribute__((packed)) S {
    int x;
    char c;
    int y;
};

template<typename... Args>
void foo(Args&&... args) {}

void bar() {
    S s;
    foo(1, s.x);
}
```

I can't think of any way to make the "reference if at all possible" semantic happen in gcc so I'm afraid I'm going to have to close this as not planned cantfix, however if anyone has ideas I'm happy to reopen.

For now, the most practical solution on gcc will be to workaround it either with
```
ASSERT(+s.a == 0);
```
Or
```
ASSERT(auto(s.a) == 0);
```
