### ISSUE TITLE
fmt Integration is Broken

### ISSUE THREAD

**Issue by robert-harrison-klein** [jeremy-rifkin/libassert#89]
Hello!

I don't think `fmt` integration currently works. You define a target, `libassert::assert`, and specify that users can add a compile definition `LIBASSERT_USE_FMT` to enable `fmt` integration on the target. However, you never link the `fmt::fmt` library to `libassert::assert`, so enabling `LIBASSERT_USE_FMT` results in a failure to compile. Specifically:

```
libassert/include/libassert/assert.hpp:50:11: fatal error: 'fmt/format.h' file not found
```

I think the fix is pretty straightforward. I think you just need to add a `CMake` option for `fmt` integration that will conditionally link `libassert::assert` to `fmt::fmt`.

Best,
Rob

**Comment by jeremy-rifkin** [comment]
Hi Rob,
This is intentional. `LIBASSERT_USE_FMT` is turns on the relevant code in the assert.hpp header and it's relying on the user having already appropriately installed fmt or linked against fmt::fmt. The thought was if a user is using this flag they should already be using fmt in their codebase. I'm happy to revisit this however presently I figured it was best to not try to have libassert manage this dependency.

**Comment by robert-harrison-klein** [comment]
Thanks for the help with this Jeremy. I finally figured out what I was doing wrong. I was including both fmt and libassert as subdirectories of my own project. Now that I am properly building and installing them as dependencies and using find_package in my CMakeLists.txt, fmt integration appears to work as intended.

**Comment by jeremy-rifkin** [comment]
Excellent! I’m glad you got it working!
